# A minimal left prompt
format = """$shlvl$directory$conda$git_branch$git_status$all"""
palette = "catppuccin_mocha"
[line_break]
disabled = true

[time]
disabled = true
format = "[$time]($style)"

[shlvl]
disabled = true
threshold = 1
symbol = "↕️ "
format = '[$symbol$shlvl]($style) '

[directory]
read_only = " "
truncation_length = 4
truncation_symbol = '.../'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[package]
disabled = true

[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

[rlang]
symbol = ' '
format = '[$symbol$version]($style) '

[cmd_duration]
format = '\[[⏱ $duration]($style)\] '
disabled = true

[conda]
format = '[$symbol$environment]($style) '
ignore_base = false

[git_metrics]
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
