# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Minimal left prompt
format = """$hostname\
	 $directory\
	 $vagrant\
	 $conda\
	 $git_branch$git_status\
	 $character"""

[username]
show_always = true
#style_user = "bg:color_orange fg:color_fg0"
#style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[character]
success_symbol = "[ ](bold green)"
error_symbol = "[ 󰜝](bold red)"
vimcmd_symbol = "[ ](bold green)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[git_branch]
symbol = " "
format = '[\[$symbol$branch\]]($style)'

[conda]
symbol = '🅒 ' 
format = '[\[$symbol$environment\]]($style)'
ignore_base = false

[vagrant]
format = '[\[[$symbol$version]($style)\]]($style)'
version_format = '${raw}'
symbol = 'V '

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = false
format = '[$path]($style)[$read_only]($read_only_style) ' 

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "

[os]
disabled = false
#style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname: ]($style)'
trim_at = '.companyname.com'
disabled = false

