-- For nvim 0.12
-- -- In case remove pack dir

-- vim.pack.add({
--   { src = "https://github.com/neovim/nvim-lspconfig.git"},
--   { src = "https://github.com/mason-org/mason.nvim.git"},
--   { src = "https://github.com/nvim-treesitter/nvim-treesitter.git" },
--   { src = "https://github.com/mfussenegger/nvim-ansible.git"},
--   { src = "https://github.com/ibhagwan/fzf-lua.git", priority = 1000},
--   { src = "https://github.com/vague2k/vague.nvim", priority = 1000},
-- })
