## ls
alias ls='ls --color=auto'
alias ll="ls -lah --color=auto"
alias l.='ls -d .* --color=auto'
alias ld="ls -lh --group-directories-first --color=auto"

## cd
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../../"
alias .....="cd ../../../../"

## grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
